### ISSUE TITLE
What kind of scene does longcat use?

### ISSUE THREAD

**Issue by rfyiamcool** [mattn/longcat#1]
can u provide longdog ? thank u 😅

**Comment by 0Delta** [comment]
Now longcat can use custom image. https://github.com/mattn/longcat/pull/12
If you can create dog image of separated three, `longcat` can transformation to `longdog` with `longcat -d /path/to/dogimages` !

**Comment by 0Delta** [comment]
Oops, it sounds very important.
I create `longdog`. It *not* cats clone.
https://github.com/0Delta/longdog
How about this ?

**Comment by rfyiamcool** [comment]
good
