### ISSUE TITLE
It could be possible to Put the negative number argment.

### ISSUE THREAD

**Issue by m-masaki72** [mattn/longcat#21]
If you put the argument "-1",  something like that.
![スクリーンショット 2019-09-24 15 20 04](https://user-images.githubusercontent.com/11995135/65486497-90355b80-dedf-11e9-8d5e-6ac0f2776ac4.png)

**Comment by mattn** [comment]
It is known issue. But I'm not going to fix this.

https://twitter.com/mattn_jp/status/1171216682905325568

**Comment by m-masaki72** [comment]
I see.
