### ISSUE TITLE
Check iTerm2/Terminal.app with DA2

### ISSUE THREAD

**Issue by mattn** [mattn/longcat#27]
Terminal.app return 1;95;0
iTerm2 return 0;95;0

**Comment by yoichi** [comment]
iTerm2 version < 3 (which doesn't support inline image protocol) return 0;95;

**Comment by mattn** [comment]
Closed by https://github.com/mattn/longcat/pull/32

**Comment by yoichi** [comment]
Could you update the image on dockerhub?
The latest image still shows sixel image on iTerm2. The expected behavior is shows image by iiTerm2 image protocol.

![スクリーンショット 2020-07-17 23 30 24](https://user-images.githubusercontent.com/107537/87797608-e9fb7d80-c885-11ea-9885-5181656894ea.png)

**Comment by mattn** [comment]
Enabled automated build on docker-hub just now.

**Comment by yoichi** [comment]
Thanks!
