### ISSUE TITLE
Longcat is not finished until  key inputs.

### ISSUE THREAD

**Issue by toca** [mattn/longcat#33]
I'm trying on WSL2 and Windows Terminal.
longcat is not finished. (no output) However, when I pressed some key twice, the image was displayed.

I think  "os.Stdout.Read(b[:])"  seems to be blocking.

**Comment by yoichi** [comment]
I've reproduced the problem with Windows Terminal v1.1.2021.0.

The problem is gone with Windows Terminal Preview v1.2.2022.0 which supports DA2
https://github.com/microsoft/terminal/releases/tag/v1.2.2022.0

**Comment by toca** [comment]
Thank you!!!!
I'll wait for v1.2.2022.0 release.

**Comment by yoichi** [comment]
Windows Terminal v1.2.2381.0 has been released!
https://github.com/microsoft/terminal/releases/tag/v1.2.2381.0
