### ISSUE TITLE
Add info of Archlinux AUR package + add license file?

### ISSUE THREAD

**Issue by Chasarr** [mattn/longcat#40]
Hi!

I just created an [AUR package for longcat](https://aur.archlinux.org/packages/longcat/) to make it easier for people running Archlinux or Manjaro to install the program. If you want you could make a note of it in the readme file, or I could edit it in a pull request.

Also how about adding a proper license file? When I created the package I got a couple of warnings telling me that I didn't include any license file to the package.

**Comment by mattn** [comment]
Thanks.

**Comment by mattn** [comment]
Something another to do ? updating README ?

**Comment by Chasarr** [comment]
Nothing serious. I usually see a LICENSE file containing a copy of the license in most repos, and when packaging it I got a warning of not including a path to the actual LICENSE file. But this is probably not too important  ¯\_(ツ)_/¯

**Comment by Chasarr** [comment]
Oh I see you added it in. Thanks!
