### ISSUE TITLE
Does not work correctly in iTerm or Terminal on Mac

### ISSUE THREAD

**Issue by mattn** [mattn/longcat#44]
https://twitter.com/shun_tagami/status/1514187826459713538

![image](https://user-images.githubusercontent.com/10111/163202519-fd34417a-71a1-462b-973d-4d5130573b44.png)

![image](https://user-images.githubusercontent.com/10111/163202547-8d05af9a-ccf9-4a71-8498-aac613fc33bb.png)

Help wanted.

**Comment by toricls** [comment]
Quickly tested and it looked really fine to me :)

<img width="314" alt="image" src="https://user-images.githubusercontent.com/3761357/163205446-e250034d-a9f1-430d-b3f6-a23120f75679.png">

Tested on:
- M1 Pro MacBook Pro (macOS Monterey v12.3.1)
- iTerm2 Build 3.4.15

**Comment by mattn** [comment]
Probably, these conditions might not work.

https://github.com/mattn/longcat/blob/8bdd3bd90f66f5ca0476981fb34cff7558b5bf15/main.go#L201

https://github.com/mattn/longcat/blob/8bdd3bd90f66f5ca0476981fb34cff7558b5bf15/main.go#L221

**Comment by mattn** [comment]
One possibility is that it might run on tmux.

**Comment by a-skua** [comment]
Reproduced in my Terminal.app (Apple M1 macOS 12.1)
<img width="682" alt="Screen Shot 2022-04-13 at 23 46 12" src="https://user-images.githubusercontent.com/41745521/163207588-7b1b871f-7495-4630-be88-374826dec98b.png">
<img width="682" alt="Screen Shot 2022-04-13 at 23 46 31" src="https://user-images.githubusercontent.com/41745521/163207610-a40edc22-9db7-4ef6-8990-b312834d32bd.png">

Intel as well (macOS 12.2.1)

**Comment by a-skua** [comment]
my environments
M1
```
asuka@asuka ~ % uname -a
Darwin asuka.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64
```
Intel
```
TODO
```

**Comment by a-skua** [comment]
@mattn 
<img width="682" alt="Screen Shot 2022-04-14 at 0 02 12" src="https://user-images.githubusercontent.com/41745521/163210665-471aa5fe-bc2b-43c0-891c-4963425a6574.png">

**Comment by mattn** [comment]
Thanks. Sorry, one more take.

```
$ echo -e "\x1b[>c" | od -x
```
(Sorry, I don't know mac have od command)

**Comment by a-skua** [comment]
@mattn 
```
asuka@asuka ~ % echo -e "\x1b[>c" | od -x
0000000      5b1b    633e    000a                                        
0000005
asuka@asuka ~ % 
```
<img width="682" alt="Screen Shot 2022-04-14 at 0 11 09" src="https://user-images.githubusercontent.com/41745521/163212351-2b9e1ced-e6d4-48a7-9b93-33b618847228.png">

**Comment by mattn** [comment]
I'll keep this open until get response from tweet author. I'd say thanks again.

**Comment by shuntagami** [comment]
Hi, I'm author of the tweet.
As in this conversation, -it flag solved this issue for iTerm2, but not for Terminal.app. (Cat is  blurred 😢 )
![screenshot](https://user-images.githubusercontent.com/69618840/163347574-bc062f77-329b-49b4-ab85-fa1307baab9d.png)
 
FYI: It seems that tmux session is not launched for Terminal.app.

**Comment by mattn** [comment]
As far as I know, Terminal.app does not method to display images.

**Comment by shuntagami** [comment]
@mattn Oh, I didn't know that. Thanks.

**Comment by shuntagami** [comment]
Really nice 😸 
<img width="1438" alt="screenshot 3" src="https://user-images.githubusercontent.com/69618840/163351240-bced9eda-d427-49db-8c3b-2956c97d919d.png">

**Comment by mattn** [comment]
Then, I'll close this since problem is solved. Thanks all!
